[project]
name = "protected-testnet-database"
authors = ["Database Security Team <security@web3database.org>"]
description = "A secure, decentralized database management system for sensitive testnet information"
telemetry = false
requirements = []

[contracts.testnet-database-core]
path = "contracts/testnet-database-core.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = true
trusted_sender = false
trusted_caller = false
callee_filter = true
